---
title: "Exams"
---

## Exams Overview

### Midterm Exams

Two exams will be given during the term, and each will have both an in-class and take-home component. Tentatively, the exams are scheduled for:

- Exam 1, Friday 9/30 (Week 6)
- Exam 2, Friday 11/11 (Week 11)

Take-home exams will be posted by 9am on Friday of the exam day and due by 11:59pm the following Monday. They are intended to take between 2 and 3 hours to complete and allow reference to course notes and the textbook. No homework will assigned the week of exams. **Except in the case of illness or emergency, requests to reschedule an in-class exam must be made a week before the exam.**

More information about the midterms (including logistics, topics and study guides) will be posted in the two weeks before the exam.

### Final Exam

The final exam will consist of two parts:

1. A cumulative take-home final exam, published at 9am on Tuesday 12/13 and due by 5pm on Friday 12/16.
2. A brief oral exam, individually scheduled for a 20-minute block during finals week.

There will not be an in-class portion for the final exam.

More information about the final exam will be posted after Thanksgiving break.

## Midterm Exam 1 Information

The first midterm will consist of two parts: an in-class exam on Friday 9/30 and a take-home exam, distributed on Friday 9/30 and due on Monday 10/3.

### Content

The exam will include material covered in class through Friday 9/23, corresponding to Chapter 1 (1.1 - 1.6), Chapter 2 (2.1 - 2.10), Chapter 3 (3.1 - 3.11) and parts of Chapter 4 (4.1 - 4.3) of Blitzstein's *Introduction to Probability*. 

The in-class component **will not** include an R coding questions, while the take-home component **will** include R coding questions.

### In-Class Component

#### Format

The in-class exam will be administered as a handwritten paper exam during class time on Friday 9/30. Questions on the in-class exam will be similar in difficulty and scope to questions from both Daily Assignments and Class Activities.

#### Resources

You may bring a page (back and front) of standard 8.5 x 11 paper with handwritten notes to the in-class exam. No other sources should be referenced during the exam. Neither calculator nor computer are required, or may be used, for the exam.

### Take-home Component

#### Format

The take-home exam will be posted on PWeb at 9am on Friday 9/30 and will be due on Gradescope by 11:59pm on Monday 10/3. Questions on the take-home exam will be similar in difficulty and scope to questions on homework.

You may take up to 3 hours to complete the exam, but these 3 hours do not need to be consecutive. You should monitor your own time, and then record on the exam your estimate for the total amount of time you actively worked on the exam.

Your solutions should be neatly written or typed. If you scan a handwritten assignment, be sure to review the legibility of your scan and upload before you submit your assignment.

#### Resources

You may use any notes you've taken for this class, your work on any previous homework, in-class, and daily assignments, any solutions posted to the course PWeb site, comments you've received on homework or assignments through gradescope, aand Blitzstein's textbook. You may also rewatch any of Blitzstein's youtube videos assigned for daily assignments (although the time you spend watching does count towards your time spent on the exam).

You may also use WolframAlpha, Maple, Mathematica, or Symbolab to assist with calculating integrals, derivatives, or algebraic simplification. If you use technology to assist calculating, please clearly reference the cite you used to assist you, and write down the explicit expression / code you input.

For problems asking you to do analysis or perform computations using R, you may use either a local installation of R or the Grinnell RStudio server, and you may reference any of the R help files available within RStudio.

You may not use any other resources other than those listed above. You may not seek answers to exam questions online or in other textbooks, and may not work with others on the exam.

### Preparation

To prepare for the exam, you should attempt to accurately assess what topics you have mastered and which you need to practice more. As a starting point, it may be helpful to review the **Objectives** listed on each Daily Assignment.

You may also find it helpful to create your own study guide with summaries of the important concepts, theorems and definitions. Look at the **Recap** section of each chapter of the textbook for inspiration for what a summary might look like.

Additionally, you should look back through previous Daily Assignments, Class Activities and Homework, paying careful attention to problems you did not complete or get correct. Try to identify any commonalities among the problems you missed, and work to improve in these areas.

### Review Problems

For extra practice, several additional review problems (along with their solutions) are printed in the .pdf linked below. I've tried to sort the problems by whether I think they are more appropriate as an in-class question or as a take-home question. While these questions are representative of the typical scope and difficulty of individual exam questions, this review is not comprehensive, nor does it necessarily represent the total amount of time available for the exam. 

- [Review Problems](exams/Midterm 1 Review.pdf)

- [Review Problems Solutions](exams/Midterm 1 Review Solutions.pdf)
  - Solutions updated on Thursday 9/29:
    - The final probability in In-Class 7c should be $\frac{1}{9}$ rather than $\frac{1}{10}$ (i.e. there are 9 numbers in the set $\{1, 2, \dots, 9 \}$.)
    - The original solution for In-Class problem 3 was answering a slightly different question, where the box had just 2 coins (a fair and a double-headed coin), instead of 3. The final answer to each part doesn't actually change (good review: think about why!), although the intermediate steps did change.
    
    
## Midterm Exam 2 Information

The first midterm will consist of two parts: an in-class exam on Friday 11/11 and a take-home exam, distributed on Friday 11/11 and due on Monday 11/14

### Content

The exam will be lightly cumulative, but with emphasis on material covered since the 1st midterm. In particular, it will include material covered in class through Friday 11/4, corresponding to Chapter 4, Chapter 5, Chapter 6, and parts of Chapter 7 (7.1, 7.2, 7.3) of Blitzstein's *Introduction to Probability*. 

The in-class component **will not** include an R coding questions, while the take-home component **will** include R coding questions.

### In-Class Component

#### Format

The in-class exam will be administered as a handwritten paper exam during class time on Friday 11/11 Questions on the in-class exam will be similar in difficulty and scope to questions from both Daily Assignments and Class Activities.

#### Resources

You may bring a page (back and front) of standard 8.5 x 11 paper with handwritten notes to the in-class exam. No other sources should be referenced during the exam. Neither calculator nor computer are required, or may be used, for the exam.

### Take-home Component

#### Format

The take-home exam will be posted on PWeb at 5pm on Friday 11/11 and will be due on Gradescope by 11:59pm on Monday 11/14 Questions on the take-home exam will be similar in difficulty and scope to questions on homework.

You may take up to 3 hours to complete the exam, but these 3 hours do not need to be consecutive. You should monitor your own time, and then record on the exam your estimate for the total amount of time you actively worked on the exam.

Your solutions should be neatly written or typed. If you scan a handwritten assignment, be sure to review the legibility of your scan and upload before you submit your assignment.

#### Resources

You may use any notes you've taken for this class, your work on any previous homework, in-class, and daily assignments, any solutions posted to the course PWeb site, comments you've received on homework or assignments through gradescope, aand Blitzstein's textbook. You may also rewatch any of Blitzstein's youtube videos assigned for daily assignments (although the time you spend watching does count towards your time spent on the exam).

For problems asking you to do analysis or perform computations using R, you may use either a local installation of R or the Grinnell RStudio server, and you may reference any of the R help files available within RStudio.

You may not use any other resources other than those listed above. You may not seek answers to exam questions online or in other textbooks, and may not work with others on the exam.

### Preparation

To prepare for the exam, you should attempt to accurately assess what topics you have mastered and which you need to practice more. As a starting point, it may be helpful to review the **Objectives** listed on each Daily Assignment.

You may also find it helpful to create your own study guide with summaries of the important concepts, theorems and definitions. Look at the **Recap** section of each chapter of the textbook for inspiration for what a summary might look like.

Additionally, you should look back through previous Daily Assignments, Class Activities and Homework, paying careful attention to problems you did not complete or get correct. Try to identify any commonalities among the problems you missed, and work to improve in these areas.

### Review Problems

For extra practice, several additional review problems (along with their solutions) are printed in the .pdf linked below. I've tried to sort the problems by whether I think they are more appropriate as an in-class question or as a take-home question. While these questions are representative of the typical scope and difficulty of individual exam questions, this review is not comprehensive, nor does it necessarily represent the total amount of time available for the exam. 

- [Review Problems](exams/Midterm 2 Review.pdf)

- [Review Problems Solutions](exams/Midterm 2 Review Solutions.pdf)