---
title: "Homework"
---

After each class session, several homework problems will be assigned, due the following Monday by 11:59pm. Homework should be submitted to [Gradescope](https://www.gradescope.com/courses/425901) and may either be typed and uploaded as a .pdf, or handwritten and scanned as an image. 

#### Extensions

Up to twice throughout the term, an extension may be requested on a homework assignment. Except in extraordinary circumstances, requests must be made prior to an assignment's due date.



## Assignments

### Homework 1

- [Homework 1](homework/HW_1.pdf), due 9/5

### Homework 2

- [Homework 2](homework/HW_2.pdf), due 9/12

### Homework 3

- [Homework 3](homework/HW_3.pdf), due 9/19

### Homework 4

- [Homework 4](homework/HW_4.pdf), due 9/26

### No HW due 10/3

### Homework 5

- [Homework 5](homework/HW_5.pdf), due 10/10

  - Homework 5 updated on Thursday 10/6
  
  - *NOTE:* An earlier version of this assignment erroneously included Problem 5 from **Chapter 5**, instead of the intended Problem 5 from **Chapter 4**. The latest version of HW 5 now correctly lists Problem 5 from Chapter 4.
  
### Homework 6

- [Homework 6](homework/HW_6.pdf), due 10/24 (after Fall Break)

  - Homework 6 updated on Tuesday 10/11
  
### Homework 7

- [Homework 7](homework/HW_7.pdf), due 11/2

  - Note: the due date for HW 7 was postponed to 11/2 (from its original due date of 10/31)
  
### Homework 8

- [Homework 8](homework/HW_8.pdf), due 11/7

  - *Updated 11/1.* Previously, HW 8 included an AP1 problem, although it turns out this exercise was solved in Theorem 4.8.1, so AP1 was removed from the homework set.

### Homework 9

- [Homework 9](homework/HW_9.pdf), due 11/21

  - *Updated 11/17.* Previously, HW 9 included an AP3 problem. But it turns out that solving part of this problem requires an integration technique that we won't talk about until Monday's class. So AP3 has been removed from this homework, and will instead appear on a later assignment.
  
### Homework 10

- [Homework 10](homework/HW_10.pdf), due 11/30

  - Note the atypical due date!
  
### Homework 11

- [Homework 11](homework/HW_11.pdf), due 12/7

  - Note the atypical due date!