---
title: "Resources"
---

A list of helpful resources (to be updated throughout the term)


## R and RStudio

Several helpful tutorials are available on the [Stat2Labs page](https://stat2labs.sites.grinnell.edu/RTutorials.html). 

If you are new to R or need a quick refresher, this [Introduction to R and RStudio app](https://shiny.grinnell.edu/tutorials/1_R_Intro/#section-getting-started) can get you up to speed in under an hour!
  
The [Cookbook for R](http://www.cookbook-r.com/) and the [R Graphics Cookbook](https://r-graphics.org/) are good in-depth references for the fundamentals of R and ggplot2.

For quick reference, RStudio publishes several cheatsheets, like the [Visualization Cheatsheet (ggplot2)](http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf) and the [Data Wrangling Cheatsheet (dplyr)](http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

You may find it helpful to install R and RStudio locally. This [tutorial](http://www.reed.edu/data-at-reed/software/R/r_studio.html) will guide you through the process.

## Additional Help 

### Instructor's Office Hours 

- **Office**: Noyce 2249

- **In-person Office Hours**: M 3-4pm, W 3-4pm, Th 2-3pm, F 3-4pm


Feel free to just drop-in, no appointment necessary.

 