---
title: "Schedule"
---

On this page you will find the topics for each day's class, along with the pre-class reading/video assignment, and the in-class activity.

## Week 1

### Friday 8-26


#### Topics

- Course Logistics

- Quantifying Uncertainty



#### Daily Assignment

*Note that the listed reading assignments should be completed prior to class*

- Review the [class syllabus](files/Syllabus_STA335_Fall22.pdf)

#### Class Activity

- [CA 8-26](class_activities/CA 8-26.pdf)

 
***********************************************


## Week 2

### Monday 8-29

#### Topics

- Foundations of Probability



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 8-29](daily_assignments/DA 8-29.pdf)

#### Class Activity

- [CA 8-29](class_activities/CA 8-29.pdf)


### Wednesday 8-31

#### Topics

- Set Theory

- Axioms of Probability



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 8-31](daily_assignments/DA 8-31.pdf)

#### Class Activity

- [CA 8-31](class_activities/CA 8-31.pdf)

### Friday 9-2

#### Topics

- Introduction to R and R Studio

- Using R to sample and replicate

- Intro to R and RStudio Demo

  - Files from 11am Class: [.Rmd file](files/Class Demo 9-2 11am.Rmd) and [.html output](files/Class-Demo-9-2-11am.html)
  
  - Files from 2pm Class: [.Rmd file](files/Class Demo 9-2 2pm.Rmd) and [.html output](files/Class-Demo-9-2-2pm.html)

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-2](daily_assignments/DA 9-2.pdf)

#### Class Activity

- [CA 9-2](class_activities/CA 9-2.pdf) (We didn't get to this activity today)


***********************************************


## Week 3

### Monday 9-5


#### Announcements

- Starting Week 3, Monday, Wednesday and Friday office hours are moved to **3:30 - 4:30pm** (instead of the previous 3-4pm)

#### Topics

- Conditional Probability

- Independence of Events



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-5](daily_assignments/DA 9-5.pdf)

#### Class Activity

- [CA 9-5](class_activities/CA 9-5.pdf)

#### Due

- Homework 1 due 11:59pm on Monday 9-5

### Wednesday 9-7

#### Topics

- Bayes' Rule

- The Law of Total Probability

- Prior and Posterior Probabilities



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-7](daily_assignments/DA 9-7.pdf)

#### Class Activity

- [CA 9-7](class_activities/CA 9-7.pdf)

### Friday 9-9

#### Topics

- The Monty Hall Problem

- Paradoxes and Fallacies in Conditional Probability
  
  - [Example of Simpson's Paradox](files/Simpsons_Paradox.pdf)



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-9](daily_assignments/DA 9-9.pdf)


#### Class Activity

- [CA 9-9](class_activities/CA 9-9.pdf)


***********************************************


## Week 4

### Monday 9-12


 

#### Topics

- Conditioning as Problem-Solving Strategy

- Conditional Probability in R

- Loops in R Demo

  - Files from 11am Class: [.Rmd file](files/Class_Demo_9-12_11am.Rmd) and [.html output](files/Class_Demo_9-12_11am.html)
  
  - Files from 2pm Class: [.Rmd file](files/Class_Demo_9-12_2pm.Rmd) and [.html output](files/Class_Demo_9-12_2pm.html)



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-12](daily_assignments/DA 9-12.pdf)

#### Class Activity

- [CA 9-12](class_activities/CA 9-12.pdf) 

  - We didn't get to this class activity in class today. If you missed class, instead review the Class Demo .Rmd file for either 11am or 2pm.

#### Due

- Homework 2 due 11:59pm on Monday 9-12

### Wednesday 9-14

#### Topics

- Random Variables

- The PMF of a random variable

- Examples of Random Variables: Bernoulli and Binomial


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-14](daily_assignments/DA 9-14.pdf)

#### Class Activity

- [CA 9-14](class_activities/CA 9-14.pdf) 

### Friday 9-16

#### Topics

- Further Examples of Random Variables: Hypergeometric and Discrete Uniform

- The CDF of a random variable



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-16](daily_assignments/DA 9-16.pdf)


#### Class Activity

- [CA 9-16](class_activities/CA 9-16.pdf) 


***********************************************

## Week 5

### Monday 9-19


 

#### Topics

- Functions of Random Variables

- Independence of Variables

- Simulating Discrete Variables in R


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-19](daily_assignments/DA 9-19.pdf)

#### Class Activity

- [CA 9-19](class_activities/CA 9-19.pdf) 



#### Due

- Homework 3 due 11:59pm on Monday 9-19

### Wednesday 9-21

#### Topics

- Expected Value of a Random Variable

- Linearity of Expectation

- The Law of the Unconscious Statistician


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-21](daily_assignments/DA 9-21.pdf)

#### Class Activity

- [CA 9-21](class_activities/CA 9-21.pdf) 

### Friday 9-23

#### Topics

- Infinite Series

- The Geometric and Negative Binomial Distributions

- Discuss logistics for the first midterm (see details on the [Exams](exams.html) page)

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-23](daily_assignments/DA 9-23.pdf)

#### Class Activity

-  [CA 9-23](class_activities/CA 9-23.pdf)

***********************************************

## Week 6

### Monday 9-26


 

#### Topics

- Indicator Random Variables

- The Fundamental Bridge


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-26](daily_assignments/DA 9-26.pdf)

#### Class Activity

- [CA 9-26](class_activities/CA 9-26.pdf)


#### Due

- Homework 4 due 11:59pm on Monday 9-26

### Wednesday 9-28

#### Topics

- Review for Midterm


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 9-28](daily_assignments/DA 9-28.pdf)

#### Class Activity

- None

### Friday 9-30

#### Topics

- In-Class Midterm 

- Take-home midterm available on PWeb at 9am (in the Midterm Folder of the Documents tab)

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- None

#### Class Activity

-  None


***********************************************

## Week 7

### Monday 10-3


 

#### Topics

- More practice with the fundamental bridge


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- None

#### Class Activity

- [CA 10-3](class_activities/CA 10-3.pdf)

  - This is very similar to the activity from 9-26, which didn't get to during class last week


#### Due

- Midterm 1 Take-Home due 11:59pm on Monday 10-3


### Wednesday 10-5

#### Topics

- Poisson Distribution

- The Poisson Paradigm


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-5](daily_assignments/DA 10-5.pdf)

#### Class Activity

- [CA 10-5](class_activities/CA 10-5.pdf)

### Friday 10-7

#### Topics

- Continuous Random Variables

- Variance

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-7](daily_assignments/DA 10-7.pdf)

#### Class Activity

- [CA 10-7](class_activities/CA 10-7.pdf) 




***********************************************

## Week 8

### Monday 10-10


 

#### Topics

- The Uniform Distribution

- Universality of the Uniform


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-10](daily_assignments/DA 10-10.pdf)

#### Class Activity

- [CA 10-10](class_activities/CA 10-10.pdf) 

### Wednesday 10-12

#### Topics

- Normal Random Variables

- Continuous Variables in R


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-12](daily_assignments/DA 10-12.pdf)

#### Class Activity

- [CA 10-12](class_activities/CA 10-12.pdf) 

- In-class R demo

  - Demo 11am [.pdf](files/RVs-in-R_11am.pdf) and [.Rmd](files/RVs-in-R_11am.Rmd)

### Friday 10-14

#### Topics

- The Exponential Variable

- Connections between The Exponential and the Poisson variables

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-14](daily_assignments/DA 10-14.pdf)

#### Class Activity

- [CA 10-14](class_activities/CA 10-14.pdf) 


***********************************************

## Fall Break 10-15 - 10-23

Class resumes Monday, 10-24


***********************************************

## Week 9

### Monday 10-24


 

#### Topics

- Moments of Random Variables

- Sample Moments


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-24](daily_assignments/DA 10-24.pdf)

#### Class Activity

- [CA 10-24](class_activities/CA 10-24.pdf)

### Wednesday 10-26

#### Topics

- Power Series

- Taylor Series


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-26](daily_assignments/DA 10-26.pdf)

#### Class Activity

- No CA for 10-26. But [lecture notes are available here.](files/Taylor Series.pdf)

### Friday 10-28

#### Topics

- The Moment Generating Function

- Moment Generating Functions and Sums

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-28](daily_assignments/DA 10-28.pdf)

#### Class Activity

- [CA 10-28](class_activities/CA 10-28.pdf)





***********************************************

## Week 10

### Monday 10-31


 

#### Topics

- Jointly Distributed Random Variables (Discrete)


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 10-31](daily_assignments/DA 10-31.pdf)

#### Class Activity

- [CA 10-31](class_activities/CA 10-31.pdf)

### Wednesday 11-2

#### Topics

- Jointly Distributed Random Variables (Continuous, Hybrid)



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-2](daily_assignments/DA 11-2.pdf)

#### Class Activity

- [CA 11-2](class_activities/CA 11-2.pdf)

### Friday 11-4

#### Topics

- 2D LOTUS

- Covariance and Correlation

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-4](daily_assignments/DA 11-4.pdf)

#### Class Activity

- [CA 11-4](class_activities/CA 11-4.pdf)


***********************************************

## Week 11

### Monday 11-7


 

#### Topics

- The multinomial distribution


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-7](daily_assignments/DA 11-7.pdf)

#### Class Activity

- [CA 11-7](class_activities/CA 11-7.pdf)


### Wednesday 11-9

#### Topics

- Review for Midterm


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-9](daily_assignments/DA 11-9.pdf)

#### Class Activity

- None

### Friday 11-11

#### Topics

- In-Class Midterm 

- Take-home midterm available on PWeb at 5pm (in the Midterm Folder of the Documents tab)

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- None

#### Class Activity

-  None


***********************************************

 

## Week 12

### Monday 11-14


 

#### Topics

- Review: Change-of-Variables from Multivariate Calculus


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- No required reading; but for additional reference or review, consider the following resources:
  - [Whitman Community Calculus: Polar Coordinates](https://www.whitman.edu/mathematics/calculus_late_online/section17.02.html)
  - [Whitman Community Calculus: Cylindrical and Spherical Coordinates](https://www.whitman.edu/mathematics/calculus_late_online/section17.06.html)
  - [Whitman Community Calculus: Change of Variables](https://www.whitman.edu/mathematics/calculus_late_online/section17.07.html)

#### Class Activity

- None

  - But here are my [lecture notes](lecture_notes/Change-of-Variables.pdf) from Monday


### Wednesday 11-16

#### Topics

- Change-of-Variables Formula for Single and Multiple Random Variables

  - Here are my [lecture notes](lecture_notes/Transformations_RV.pdf) from Wednesday


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-16](daily_assignments/DA 11-16.pdf)

#### Class Activity

- [CA 11-16](class_activities/CA 11-16.pdf)

### Friday 11-18

#### Topics

- The Gamma Distribution

- Poisson Processes

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-18](daily_assignments/DA 11-18.pdf)

#### Class Activity

-  [CA 11-18](class_activities/CA 11-18.pdf)


***********************************************


## Week 13

### Monday 11-21


 

#### Topics

- The Gamma Distribution

- Poisson Processes



#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- No new daily assignment; however, you may want to review your answers to DA 11-18

  - Additionally, I've reopened DA 11-18 on gradescope until Monday 11-21 at 10am, so if you did not complete this DA for Friday, you can do so now.

#### Class Activity

-  [CA 11-21](class_activities/CA 11-18.pdf)


#### Additional Resources

- Although not specifically related to the Gamma Distribution, [this video](https://www.youtube.com/watch?v=KuXjwB4LzSA&ab_channel=3Blue1Brown) by 3Blue1Brown might be helpful to understand the convolution formula that appears in the PDF of a sum of random variables.


### Wednesday 11-23

#### Topics

- The Beta Distribution

- Beta and Gamma Correspondence

- Here are [lecture notes](lecture_notes/Beta.pdf) from today's class.

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-23](daily_assignments/DA 11-23.pdf)


#### Class Activity

- [CA 11-23](class_activities/CA 11-23.pdf)

### Friday 11-25

 
No class; thanksgiving holiday


***********************************************

 

## Week 14

### Monday 11-28


 

#### Topics

- Conditional expectation given an event


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-28](daily_assignments/DA 11-28.pdf)

#### Class Activity

- [CA 11-28](class_activities/CA 11-28.pdf)


### Wednesday 11-30

#### Topics

- Condition expectation given a random variable

- Properties of conditional expectation

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 11-30](daily_assignments/DA 11-30.pdf)

#### Class Activity

- [CA 11-30](class_activities/CA 11-30.pdf)

### Friday 12-2

#### Topics

-  Conditional Variance

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 12-2](daily_assignments/DA 12-2.pdf)


#### Class Activity

- [CA 12-2](class_activities/CA 12-2.pdf)





***********************************************

 

## Week 15

### Monday 12-5


 

#### Topics

- Multivariate Normal

  - [Visualizing Bivariate Normal](files/MVN.html)


#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 12-5](daily_assignments/DA 12-5.pdf)

#### Class Activity

- CA 12-5 (We didn't get to the class activity today.)

  - Here are my [lecture notes](lecture_notes/MVN.pdf) from today.




### Wednesday 12-7

#### Topics

- Inequalities

- The Law of Large Numbers

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 12-7](daily_assignments/DA 12-7.pdf)

#### Class Activity

- [CA 12-7](class_activities/CA 12-7.pdf)

### Friday 12-9

#### Topics

-  The Central Limit Theorem

#### Daily Assignment

*Note that the listed reading assignments should be completed by 10am and submitted to [Gradescope](https://www.gradescope.com/courses/425901)*

- [DA 12-9](daily_assignments/DA 12-9.pdf)


#### Class Activity

- No class activity for 12-9. But a coding demo will be posted here after class.


***********************************************